--- !PWDGEN_SETTINGS

  - settings:
      dictionary: "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz?@()1234567890_-+<>,."
      db_path: ".db_pwd.csv"
      headers: "Ora,Data,Password"
      pwd_len: 12
